### ISSUE TITLE
Consider GitPack support for easier installation

### ISSUE THREAD

**Issue by dominiksalvet** [rien/reStream#104]
Hello Rien,
I was just going briefly through rMview and reStream and I just quickly noticed that reStream is basically an Sh script. The first thought that came into my mind was that I could let you know about a program that I developed few years ago (still perfectly works as intended). In short, it is a POSIX-friendly Sh script installer for Git-based projects -- namely for simple ones like this (at least on host side).

It is called GitPack (see https://github.com/dominiksalvet/gitpack). It is basically a Git-based package manager, which is quick, simple to install, yet even simpler to use and it has tight integration with a Git repository. It can perform delta updates and requires no more work than preparing basic installation and uninstallation scripts. Users then can install reStream simply by `gitpack install https://github.com/rien/reStream` or `sudo gitpack install https://github.com/rien/reStream` (for root-based installations)... These commands can also perform update to the latest release.

If you are interested, feel free to have a look at GitPack's readme or maybe examples of already existing GitPack projects here https://github.com/topics/gitpack.

Please let me know what you think about it. :-)

**Comment by rien** [comment]
Hi Dominik

I'm not fully convinced of the system of GitPack. It seems that as a maintainer, I should make assumptions as to where the user would like the script to be installed (e.g. `~/.local/bin`). While this will work on Ubuntu, it might not work on other systems like NixOS (which I am running myself), MacOS, Windows, ....

This project has a non-standard dependency of requiring a binary to be present on the reMarkable tablet. While I could provide a way to install this through the script as well, I think it is better if users can manually execute the few simple commands that are needed so they understand how to fix it if things go wrong. In addition, `reStream` has some dependencies like `lz4` and `ffmpeg` which would need to be installed on the host system as well.

I would prefer that `reStream` is packaged through the package manager of the OS instead of having users trust that I have written a non-malicious `.install/install-global` script.

Thank you for your suggestion though, I appreciate your interest in reStream. I have considered GitPack and I'm afraid I will have to politely decline.
