### ISSUE TITLE
Streaming in color

### ISSUE THREAD

**Issue by greenwald** [rien/reStream#19]
Using the pixel_format "rgb565le", I can get color to come through, but not stably: the browser will show color:

![image](https://user-images.githubusercontent.com/2571281/79344315-f3e0ae00-7f2f-11ea-8ec8-a3f4456d9ed5.png)

But when I view a document, the color will disappear after a moment. I suppose this is a function of the reMarkable---but is there any way to overcome this?

**Comment by rien** [comment]
Oh wow. I did not realize there was also color information in the framebuffer. I guess that if the color disappears, it is actually not rendered and thus not recoverable with a simple script...

I doubt this will ever work perfectly, because the reMarkable screen is grayscale. I'm wondering what you're trying to do that you need color?

**Comment by greenwald** [comment]
I'm trying to use the reMarkable to give online lectures with slides that are in color. I suppose this has something to do with the X11 mode on the rM itself. Just no clue how to change that in the least invasive way possible.

**Comment by rien** [comment]
Odd, I don't see colors when I use `-pixel_format rgb565le`, is that the only change you did?

**Comment by rien** [comment]
How did you upload the files which have color?

**Comment by greenwald** [comment]
They were transferred using `rmapi` for the most part; some may have been transferred through the Android app. There definitely an inconsistency and temperamental nature to the appearance of color. Somehow the cover to _Cosmology_ is no longer in color in my browser since I opened and viewed the document. But other documents keep their color in the browser after I view them. No document manages to keep its color as I'm viewing it, though.

The only change I made was to the pixel format, which I arrived at by reading [this.](https://github.com/canselcik/libremarkable/wiki/Framebuffer-Overview)

**Comment by rien** [comment]
I guess thumbnails generated on the rM itself will be in grayscale, while thumbnails generated on a device that supports color will be shown in color...

I've taken a look and there is no X11 running on the rM, `xochitl` is writing directly to the framebuffer. So achieving color won't be simple, I'm afraid.

**Comment by greenwald** [comment]
Bummer. Thanks.

**Comment by torwag** [comment]
> I'm trying to use the reMarkable to give online lectures with slides that are in color. I suppose this has something to do with the X11 mode on the rM itself. Just no clue how to change that in the least invasive way possible.

I too give online lectures and tried your method. However, finally I settled for the vice versa way, using the rM with [rmvncclient](https://github.com/matteodelabre/rmvncclient). 
Instead of the usage scenario in the README, to create an virtual screen and to move the application onto the rM (which has it's own merits and use cases) I simply use the rM to copy a part of my existing screens. 
With that I can e.g. copy the slide of my presentation tool to the rM and use the pen to draw onto the slide (if your presentation tool supports this). On my real monitor I can still see everything in colour. On the rM it is gray scale but this is most of the time no problem. There is a bit of a lack, which makes writing not as smooth as it could be but it is ok.
